import './globals.css'
import CustomNavbar from 'components/CustomNavbar'
import CustomFooter from 'components/CustomFooter'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <div style={{maxWidth: '650px', margin: 'auto'}}>
          <CustomNavbar />
          {children}
        </div>
        <CustomFooter />
      </body>
    </html>
  )
}
